version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - md-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
    expose:
      - "3306"

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp-data:/var/www/html/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
    expose:
      - "9000"

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: requirements/nginx
    volumes:
      - wp-data:/var/www/html/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always 
    ports:
      - "443:443"

networks:
  inception:
    driver: bridge
    name: inception
    
volumes:
  md-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yeselee/data/mariadb
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yeselee/data/wordpress